# kubectl apply -f ms-producto-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ms-producto-secret
  namespace: ms-producto-namespace
type: Opaque
data:
  # echo -n "valor" | base64
  DB_HOST: ZXAtd2FuZGVyaW5nLWZsb3dlci1hdHI5bm5jeC1wb29sZXIuYy05LnVzLWVhc3QtMS5hd3MubmVvbi50ZWNo
  DB_PORT: NTQzMg==
  DB_NAME: cHJvZHVjdG9z
  DB_USER: bmVvbmRiX293bmVy
  DB_PASSWORD: bnBnX3RJZTNCQTFSdmtKbw==
  DB_SSL_MODE: cmVxdWlyZQ==
  SERVER_PORT: ODA4MQ==
