server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-productos
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:ep-wandering-flower-atr9nncx-pooler.c-9.us-east-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:productos}?sslMode=${DB_SSL_MODE:require}&channel_binding=require
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD:npg_tIe3BA1RvkJo}
