# kubectl apply -f ms-pedido-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ms-pedido-secret
  namespace: ms-pedido-namespace
type: Opaque
data:
  # echo -n "valor" | base64
  DB_HOST: ZXAtd2FuZGVyaW5nLWZsb3dlci1hdHI5bm5jeC1wb29sZXIuYy05LnVzLWVhc3QtMS5hd3MubmVvbi50ZWNo
  DB_NAME: cGVkaWRvcw==
  DB_USER: bmVvbmRiX293bmVy
  DB_PASSWORD: bnBnX3RJZTNCQTFSdmtKbw==
  DB_SSL_MODE: cmVxdWlyZQ==
  SERVER_PORT: ODA4Mg==
  PRODUCTOS_SERVICE_URL: aHR0cDovL21zLXByb2R1Y3RvLXNlcnZpY2UubXMtcHJvZHVjdG8tbmFtZXNwYWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjgwODE=
